python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
python3 AIAPI-slave-baidu.py &
