python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
python3 naviback-slave-baidu.py &
